#!/usr/bin/env ruby

require 'json'


def cfg
  File.open(ENV['ENV_FILE']) do |f|
    @cfg ||= JSON.parse(f.read)
  end
  @cfg
end

def pad(val, n)
  val + (" " * (n-val.length))
end

puts "#{pad("NAME", 20)} STATE"
cfg.keys.each do |k|
  status = `docker container inspect --format='{{json .State.Status}}' #{k}`
  puts "#{pad(k, 20)} #{status.chomp.gsub(/"/, "")}"
end
